### ISSUE TITLE
Application start problem

### ISSUE THREAD

**Issue by pawelkat** [vytronics/vytronics.hmi#1]
Hallo, 
I wanted to install the app on my local PC. 'node install' was completed without any problems. Starting the app with 'node server' (application.js doesn't exist) does nothing, simply displays: [2014-07-31 07:36:02.770] [DEBUG] [default] - Loading sysdriver module.  
and quits.
Are there any missing dependencies?
Thanks a lot, great concept! Hope to have it running.

**Comment by vytronics** [comment]
Pawelkat - Thank you for downloading and evaluating the software. I am sorry you are having a problem. This is in the experimental stage so not everything will work smoothly. Hoping to be stable in November but you should be able to run the system on your PC. Let me give you some better instruction and let me know how it goes.

First, the vytronics.hmi repository is a node module. Therefore, unless you are going to be forking you should not clone or download this. Rather, you should create a new node application that includes a dependency on vytronics.hmi. Since I do not have an API and tutorial documentation right now the best way is to start with a sample application that I have on github.

 Try the following, assuming you have git installed on your machine:

Create a new directory on your PC and switch to it. Clone or otherwise download the repository at https://github.com/vytronics/vytronics.project.git. This is a sample SCADA project that uses a simulator driver and has a sample single page application desktop HMTL with some sample displays.

> mkdir mydir
> cd mydir
> git clone https://github.com/vytronics/vytronics.project.git

This will make a folder named vytronics.project which is a node application with a package.json including the vytronics.hmi module. The project also has a folder named "project" with the sample config file and displays. All you need to do is now install the dependencies.

> cd vytronics.hmi
> npm install

Now you can run the project

> node application

To run the client open up chrome and enter the url:
localhost:8000

Just tried this on my laptop and it works. Did this work for you?

**Comment by pawelkat** [comment]
Hi, thanks a lot, I just cloned incorrect git project. It is working perfectly now, also on the nitrous.io box! Hope I will find time to adapt it to use with my projects, have already some ideas.

**Comment by vytronics** [comment]
Glad it works. Email me direct at support@vytronics.com for any questions or help. I would like to know more about your projects so I can prioritize development for people that want to use the project
